import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { StateStore } from '../../src/state/state-store.mjs';
import { CodexCliBackend, extractSessionId } from '../../src/codex-cli/codex-cli-backend.mjs';
import { readLinuxProcessIdentity } from '../../src/git-isolation/process-identity.mjs';

const fake=fileURLToPath(new URL('./fake-codex.mjs',import.meta.url));
async function fixture(){await fs.chmod(fake,0o755);const root=await fs.mkdtemp(path.join(os.tmpdir(),'subagent-backend-'));const store=new StateStore(root);await store.create({agent_id:'sa_backend',state:'RUNNING',transition_history:[]});return {root,store};}

test('probe reports exact Codex CLI capabilities and session extraction supports nested forms',async()=>{const {root,store}=await fixture();try{const b=new CodexCliBackend({codexPath:fake,stateStore:store,parentEnv:{PATH:process.env.PATH,HOME:process.env.HOME}});const caps=await b.probe({refresh:true});assert.equal(caps.version,'codex-cli 99.0.0');assert.deepEqual({exec:caps.exec,json:caps.json,resume:caps.resume,sandboxReadOnly:caps.sandboxReadOnly,sandboxWorkspaceWrite:caps.sandboxWorkspaceWrite,approvalNever:caps.approvalNever},{exec:true,json:true,resume:true,sandboxReadOnly:true,sandboxWorkspaceWrite:true,approvalNever:true});assert.equal(extractSessionId({session:{thread:{threadId:'nested-session'}}}),'nested-session');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('spawn and followup persist structured events, session identity and redact stderr',async()=>{const {root,store}=await fixture();try{const b=new CodexCliBackend({codexPath:fake,stateStore:store,parentEnv:{PATH:process.env.PATH,HOME:process.env.HOME,CODEX_ACCESS_TOKEN:'token-123',RANDOM_SECRET:'do-not-forward'}});const h=await b.spawn({agent_id:'sa_backend',prompt:'emit-secret',cwd:process.cwd(),workspace_mode:'read_only'});assert.ok(h.pid>0);const r=await h.completion;assert.equal(r.exit_code,0);assert.match(r.session_id,/^sess-/);assert.equal(r.final_text,'completed');assert.match(r.stderr_tail,/\[REDACTED\]/);assert.doesNotMatch(r.stderr_tail,/token-123/);assert.match(await fs.readFile(path.join(root,'sa_backend','events.jsonl'),'utf8'),/thread.started/);assert.doesNotMatch(await fs.readFile(path.join(root,'sa_backend','stderr.log'),'utf8'),/token-123/);const f=await b.followup({...h,session_id:r.session_id},'again');const fr=await f.completion;assert.equal(fr.session_id,r.session_id);assert.equal(fr.final_text,'resumed');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('cancel rejects missing or mismatched process identity',async()=>{const {root,store}=await fixture();try{const b=new CodexCliBackend({stateStore:store,processProbe:async()=>({pid:42,start_ticks:'2'})});await assert.rejects(()=>b.cancel({}),e=>e.code==='CAPABILITY_UNAVAILABLE');await assert.rejects(()=>b.cancel({pid:42,process_identity:{pid:42,start_ticks:'1'}}),e=>e.code==='PROCESS_IDENTITY_MISMATCH');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('cancel terminates a matching detached process group on Linux',async(t)=>{if(process.platform!=='linux') return t.skip('Linux-only v1 containment');const {root,store}=await fixture();const child=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{detached:true,stdio:'ignore'});const exited=new Promise(resolve=>child.once('exit',resolve));try{const identity=await readLinuxProcessIdentity(child.pid);assert.ok(identity);const b=new CodexCliBackend({stateStore:store});await b.cancel({pid:child.pid,process_identity:identity},{graceSeconds:0});await exited;assert.ok(child.signalCode==='SIGTERM'||child.signalCode==='SIGKILL'||child.exitCode===0);}finally{try{process.kill(-child.pid,'SIGKILL');}catch{}await fs.rm(root,{recursive:true,force:true});}});
