import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {StateStore} from '../../src/state/state-store.mjs';
import {SubagentBroker} from '../../src/broker/broker.mjs';
import {brokerError} from '../../src/broker/protocol.mjs';
function deferred(){let resolve,reject;const completion=new Promise((res,rej)=>{resolve=res;reject=rej;});return{completion,resolve,reject};}
function workspaceManager(){return{async resolveBase(){return'a'.repeat(40);},async createWorkspace({agentId,mode,baseSha}){return{repo_root:'/repo',path:'/tmp/'+agentId,mode,base_sha:baseSha,branch:mode==='worktree_write'?'subagent/'+agentId:null};},async statusWorkspace(){return{dirty:false,porcelain:'',commits:[],diff_stat:''};},async cleanupWorkspace(){}};}
async function completedBroker({followupMode='throw'}={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'subagent-broker-failure-'));const first=deferred();const backend={async probe(){return{resume:true};},async spawn(spec){return{pid:101,process_identity:{pid:101,start_ticks:'1'},session_id:'sess-1',completion:first.completion,...spec};},async followup(handle){if(followupMode==='throw')throw new Error('resume launch failed');const d=deferred();queueMicrotask(()=>d.reject(new Error('resume child crashed')));return{...handle,pid:202,process_identity:{pid:202,start_ticks:'2'},completion:d.completion};},async cancel(){}};const store=new StateStore(root);const broker=new SubagentBroker({repoRoot:'/repo',stateStore:store,backend,workspaceManager:workspaceManager(),roleLoader:async()=> 'role',idFactory:()=> 'sa_failure'});const spawned=await broker.spawn({task:'x',role:'reviewer',workspace_mode:'read_only'});first.resolve({exit_code:0,session_id:'sess-1',final_text:'ok'});assert.equal((await broker.wait(spawned.agent_id,1000)).state,'COMPLETED');return{root,broker};}
test('followup launch failure becomes FAILED instead of remaining SPAWNING',async()=>{const {root,broker}=await completedBroker({followupMode:'throw'});try{await assert.rejects(()=>broker.followup('sa_failure','continue'),/resume launch failed/);assert.equal((await broker.status('sa_failure')).state,'FAILED');}finally{await broker.shutdown();await fs.rm(root,{recursive:true,force:true});}});
test('followup child rejection becomes FAILED instead of remaining RUNNING',async()=>{const {root,broker}=await completedBroker({followupMode:'reject'});try{await broker.followup('sa_failure','continue');const deadline=Date.now()+1000;let state;do{state=(await broker.status('sa_failure')).state;if(state==='FAILED')break;await new Promise(r=>setTimeout(r,20));}while(Date.now()<deadline);assert.equal(state,'FAILED');}finally{await broker.shutdown();await fs.rm(root,{recursive:true,force:true});}});
test('timeout containment failure is ORPHANED, not falsely TIMED_OUT',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'subagent-broker-timeout-'));const d=deferred();const backend={async probe(){return{resume:false};},async spawn(spec){return{pid:303,process_identity:{pid:303,start_ticks:'3'},session_id:'sess-timeout',completion:d.completion,...spec};},async cancel(){throw brokerError('PROCESS_IDENTITY_MISMATCH','cannot prove child identity');}};const store=new StateStore(root);const broker=new SubagentBroker({repoRoot:'/repo',stateStore:store,backend,workspaceManager:workspaceManager(),roleLoader:async()=> 'role',idFactory:()=> 'sa_timeout',defaultTimeoutSeconds:1});try{await broker.spawn({task:'hang',role:'tester',workspace_mode:'read_only',timeout_seconds:1});const deadline=Date.now()+5000;let state;do{state=(await broker.status('sa_timeout')).state;if(state==='ORPHANED')break;await new Promise(r=>setTimeout(r,25));}while(Date.now()<deadline);assert.equal(state,'ORPHANED');}finally{await broker.shutdown();await fs.rm(root,{recursive:true,force:true});}});
